name: getx_cli
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  datetime_picker_formfield_new: ^2.0.0
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_local_notifications: ^13.0.0
  get: 4.6.5
  http: 0.13.5
  timezone: ^0.9.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
